[2019-11-14 11:38:26] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /src/Controller/RegistrationController.php"" at /var/www/workflow-consolidation-challenge/vendor/symfony/http-kernel/EventListener/RouterListener.php line 138 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /src/Controller/RegistrationController.php\" at /var/www/workflow-consolidation-challenge/vendor/symfony/http-kernel/EventListener/RouterListener.php:138, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/src/Controller/RegistrationController.php/\". at /var/www/workflow-consolidation-challenge/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2019-11-14 11:38:28] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"98ce72"},"request_uri":"http://symfony.local/_wdt/98ce72","method":"GET"} []
[2019-11-14 11:54:46] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /src/Controller/RegistrationController.php"" at /var/www/workflow-consolidation-challenge/vendor/symfony/http-kernel/EventListener/RouterListener.php line 138 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /src/Controller/RegistrationController.php\" at /var/www/workflow-consolidation-challenge/vendor/symfony/http-kernel/EventListener/RouterListener.php:138, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/src/Controller/RegistrationController.php/\". at /var/www/workflow-consolidation-challenge/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2019-11-14 11:54:53] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"ed5217"},"request_uri":"http://symfony.local/_wdt/ed5217","method":"GET"} []
[2019-11-14 11:57:29] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"http://symfony.local/register","method":"GET"} []
[2019-11-14 11:57:31] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-11-14 11:57:34] php.CRITICAL: Too few arguments to function App\Entity\User::__construct(), 0 passed in /var/www/workflow-consolidation-challenge/src/Controller/RegistrationController.php on line 20 and exactly 3 expected {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Too few arguments to function App\\Entity\\User::__construct(), 0 passed in /var/www/workflow-consolidation-challenge/src/Controller/RegistrationController.php on line 20 and exactly 3 expected at /var/www/workflow-consolidation-challenge/src/Entity/User.php:61)"} []
[2019-11-14 11:57:34] request.CRITICAL: Uncaught PHP Exception ArgumentCountError: "Too few arguments to function App\Entity\User::__construct(), 0 passed in /var/www/workflow-consolidation-challenge/src/Controller/RegistrationController.php on line 20 and exactly 3 expected" at /var/www/workflow-consolidation-challenge/src/Entity/User.php line 61 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Too few arguments to function App\\Entity\\User::__construct(), 0 passed in /var/www/workflow-consolidation-challenge/src/Controller/RegistrationController.php on line 20 and exactly 3 expected at /var/www/workflow-consolidation-challenge/src/Entity/User.php:61)"} []
[2019-11-14 11:57:46] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"854615"},"request_uri":"http://symfony.local/_wdt/854615","method":"GET"} []
[2019-11-14 12:02:49] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"http://symfony.local/register","method":"GET"} []
[2019-11-14 12:02:49] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-11-14 12:02:49] php.CRITICAL: Too few arguments to function App\Entity\User::__construct(), 0 passed in /var/www/workflow-consolidation-challenge/src/Controller/RegistrationController.php on line 20 and exactly 3 expected {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Too few arguments to function App\\Entity\\User::__construct(), 0 passed in /var/www/workflow-consolidation-challenge/src/Controller/RegistrationController.php on line 20 and exactly 3 expected at /var/www/workflow-consolidation-challenge/src/Entity/User.php:61)"} []
[2019-11-14 12:02:49] request.CRITICAL: Uncaught PHP Exception ArgumentCountError: "Too few arguments to function App\Entity\User::__construct(), 0 passed in /var/www/workflow-consolidation-challenge/src/Controller/RegistrationController.php on line 20 and exactly 3 expected" at /var/www/workflow-consolidation-challenge/src/Entity/User.php line 61 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Too few arguments to function App\\Entity\\User::__construct(), 0 passed in /var/www/workflow-consolidation-challenge/src/Controller/RegistrationController.php on line 20 and exactly 3 expected at /var/www/workflow-consolidation-challenge/src/Entity/User.php:61)"} []
[2019-11-14 12:02:49] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"58526e"},"request_uri":"http://symfony.local/_wdt/58526e","method":"GET"} []
[2019-11-14 12:03:01] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"http://symfony.local/register","method":"GET"} []
[2019-11-14 12:03:01] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-11-14 12:03:01] php.CRITICAL: Too few arguments to function App\Entity\User::__construct(), 0 passed in /var/www/workflow-consolidation-challenge/src/Controller/RegistrationController.php on line 20 and exactly 3 expected {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Too few arguments to function App\\Entity\\User::__construct(), 0 passed in /var/www/workflow-consolidation-challenge/src/Controller/RegistrationController.php on line 20 and exactly 3 expected at /var/www/workflow-consolidation-challenge/src/Entity/User.php:61)"} []
[2019-11-14 12:03:01] request.CRITICAL: Uncaught PHP Exception ArgumentCountError: "Too few arguments to function App\Entity\User::__construct(), 0 passed in /var/www/workflow-consolidation-challenge/src/Controller/RegistrationController.php on line 20 and exactly 3 expected" at /var/www/workflow-consolidation-challenge/src/Entity/User.php line 61 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Too few arguments to function App\\Entity\\User::__construct(), 0 passed in /var/www/workflow-consolidation-challenge/src/Controller/RegistrationController.php on line 20 and exactly 3 expected at /var/www/workflow-consolidation-challenge/src/Entity/User.php:61)"} []
[2019-11-14 12:03:01] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"3884b5"},"request_uri":"http://symfony.local/_wdt/3884b5","method":"GET"} []
[2019-11-14 12:03:46] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"http://symfony.local/register","method":"GET"} []
[2019-11-14 12:03:46] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-11-14 12:03:46] php.CRITICAL: Too few arguments to function App\Entity\User::__construct(), 0 passed in /var/www/workflow-consolidation-challenge/src/Controller/RegistrationController.php on line 20 and exactly 3 expected {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Too few arguments to function App\\Entity\\User::__construct(), 0 passed in /var/www/workflow-consolidation-challenge/src/Controller/RegistrationController.php on line 20 and exactly 3 expected at /var/www/workflow-consolidation-challenge/src/Entity/User.php:61)"} []
[2019-11-14 12:03:46] request.CRITICAL: Uncaught PHP Exception ArgumentCountError: "Too few arguments to function App\Entity\User::__construct(), 0 passed in /var/www/workflow-consolidation-challenge/src/Controller/RegistrationController.php on line 20 and exactly 3 expected" at /var/www/workflow-consolidation-challenge/src/Entity/User.php line 61 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Too few arguments to function App\\Entity\\User::__construct(), 0 passed in /var/www/workflow-consolidation-challenge/src/Controller/RegistrationController.php on line 20 and exactly 3 expected at /var/www/workflow-consolidation-challenge/src/Entity/User.php:61)"} []
[2019-11-14 12:03:46] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"802db7"},"request_uri":"http://symfony.local/_wdt/802db7","method":"GET"} []
[2019-11-14 13:05:04] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"http://symfony.local/register","method":"GET"} []
[2019-11-14 13:05:04] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-11-14 13:05:04] php.CRITICAL: Too few arguments to function App\Entity\User::__construct(), 0 passed in /var/www/workflow-consolidation-challenge/src/Controller/RegistrationController.php on line 25 and exactly 3 expected {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Too few arguments to function App\\Entity\\User::__construct(), 0 passed in /var/www/workflow-consolidation-challenge/src/Controller/RegistrationController.php on line 25 and exactly 3 expected at /var/www/workflow-consolidation-challenge/src/Entity/User.php:62)"} []
[2019-11-14 13:05:04] request.CRITICAL: Uncaught PHP Exception ArgumentCountError: "Too few arguments to function App\Entity\User::__construct(), 0 passed in /var/www/workflow-consolidation-challenge/src/Controller/RegistrationController.php on line 25 and exactly 3 expected" at /var/www/workflow-consolidation-challenge/src/Entity/User.php line 62 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Too few arguments to function App\\Entity\\User::__construct(), 0 passed in /var/www/workflow-consolidation-challenge/src/Controller/RegistrationController.php on line 25 and exactly 3 expected at /var/www/workflow-consolidation-challenge/src/Entity/User.php:62)"} []
[2019-11-14 13:05:05] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"9321e9"},"request_uri":"http://symfony.local/_wdt/9321e9","method":"GET"} []
[2019-11-14 13:05:16] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"http://symfony.local/register","method":"GET"} []
[2019-11-14 13:05:16] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-11-14 13:05:16] php.CRITICAL: Too few arguments to function App\Entity\User::__construct(), 0 passed in /var/www/workflow-consolidation-challenge/src/Controller/RegistrationController.php on line 25 and exactly 3 expected {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Too few arguments to function App\\Entity\\User::__construct(), 0 passed in /var/www/workflow-consolidation-challenge/src/Controller/RegistrationController.php on line 25 and exactly 3 expected at /var/www/workflow-consolidation-challenge/src/Entity/User.php:62)"} []
[2019-11-14 13:05:16] request.CRITICAL: Uncaught PHP Exception ArgumentCountError: "Too few arguments to function App\Entity\User::__construct(), 0 passed in /var/www/workflow-consolidation-challenge/src/Controller/RegistrationController.php on line 25 and exactly 3 expected" at /var/www/workflow-consolidation-challenge/src/Entity/User.php line 62 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Too few arguments to function App\\Entity\\User::__construct(), 0 passed in /var/www/workflow-consolidation-challenge/src/Controller/RegistrationController.php on line 25 and exactly 3 expected at /var/www/workflow-consolidation-challenge/src/Entity/User.php:62)"} []
[2019-11-14 13:05:16] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"c77856"},"request_uri":"http://symfony.local/_wdt/c77856","method":"GET"} []
[2019-11-14 13:06:34] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"http://symfony.local/register","method":"GET"} []
[2019-11-14 13:06:34] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-11-14 13:06:35] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Neither the property "name" nor one of the methods "name()", "getname()"/"isname()"/"hasname()" or "__call()" exist and have public access in class "Symfony\Component\Form\FormView"." at /var/www/workflow-consolidation-challenge/templates/registration/register.html.twig line 9 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Neither the property \"name\" nor one of the methods \"name()\", \"getname()\"/\"isname()\"/\"hasname()\" or \"__call()\" exist and have public access in class \"Symfony\\Component\\Form\\FormView\". at /var/www/workflow-consolidation-challenge/templates/registration/register.html.twig:9)"} []
[2019-11-14 13:06:35] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"8fc8c4"},"request_uri":"http://symfony.local/_wdt/8fc8c4","method":"GET"} []
[2019-11-14 13:06:36] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"8fc8c4"},"request_uri":"http://symfony.local/_wdt/8fc8c4","method":"GET"} []
[2019-11-14 14:24:51] console.ERROR: Error thrown while running command "make:migration". Message: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES)" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"make:migration","message":"An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES)"} []
[2019-11-14 14:24:51] console.DEBUG: Command "make:migration" exited with code "1" {"command":"make:migration","code":1} []
[2019-11-14 14:25:58] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"http://symfony.local/register","method":"GET"} []
[2019-11-14 14:25:58] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-11-14 14:26:02] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Neither the property "name" nor one of the methods "name()", "getname()"/"isname()"/"hasname()" or "__call()" exist and have public access in class "Symfony\Component\Form\FormView"." at /var/www/workflow-consolidation-challenge/templates/registration/register.html.twig line 9 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Neither the property \"name\" nor one of the methods \"name()\", \"getname()\"/\"isname()\"/\"hasname()\" or \"__call()\" exist and have public access in class \"Symfony\\Component\\Form\\FormView\". at /var/www/workflow-consolidation-challenge/templates/registration/register.html.twig:9)"} []
[2019-11-14 14:26:10] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"67116a"},"request_uri":"http://symfony.local/_wdt/67116a","method":"GET"} []
[2019-11-14 14:26:44] console.ERROR: Error thrown while running command "make:migration". Message: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES)" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"make:migration","message":"An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES)"} []
[2019-11-14 14:26:44] console.DEBUG: Command "make:migration" exited with code "1" {"command":"make:migration","code":1} []
[2019-11-14 14:26:55] console.ERROR: Error thrown while running command "'make:migration:migrate'". Message: "There are no commands defined in the "make:migration" namespace.  Did you mean one of these?     doctrine:migrations     make     make:serializer" {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"make:migration\" namespace.\n\nDid you mean one of these?\n    doctrine:migrations\n    make\n    make:serializer at /var/www/workflow-consolidation-challenge/vendor/symfony/console/Application.php:592)","command":"'make:migration:migrate'","message":"There are no commands defined in the \"make:migration\" namespace.\n\nDid you mean one of these?\n    doctrine:migrations\n    make\n    make:serializer"} []
[2019-11-14 14:27:36] console.ERROR: Error thrown while running command "'docrine:migration:migrate'". Message: "There are no commands defined in the "docrine:migration" namespace.  Did you mean one of these?     doctrine     doctrine:cache     doctrine:database     doctrine:generate     doctrine:mapping     doctrine:migrations     doctrine:query     doctrine:schema" {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"docrine:migration\" namespace.\n\nDid you mean one of these?\n    doctrine\n    doctrine:cache\n    doctrine:database\n    doctrine:generate\n    doctrine:mapping\n    doctrine:migrations\n    doctrine:query\n    doctrine:schema at /var/www/workflow-consolidation-challenge/vendor/symfony/console/Application.php:592)","command":"'docrine:migration:migrate'","message":"There are no commands defined in the \"docrine:migration\" namespace.\n\nDid you mean one of these?\n    doctrine\n    doctrine:cache\n    doctrine:database\n    doctrine:generate\n    doctrine:mapping\n    doctrine:migrations\n    doctrine:query\n    doctrine:schema"} []
[2019-11-14 14:27:44] console.ERROR: Error thrown while running command "'docrine:migrations:migrate'". Message: "There are no commands defined in the "docrine:migrations" namespace.  Did you mean one of these?     doctrine     doctrine:cache     doctrine:database     doctrine:generate     doctrine:mapping     doctrine:migrations     doctrine:query     doctrine:schema" {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"docrine:migrations\" namespace.\n\nDid you mean one of these?\n    doctrine\n    doctrine:cache\n    doctrine:database\n    doctrine:generate\n    doctrine:mapping\n    doctrine:migrations\n    doctrine:query\n    doctrine:schema at /var/www/workflow-consolidation-challenge/vendor/symfony/console/Application.php:592)","command":"'docrine:migrations:migrate'","message":"There are no commands defined in the \"docrine:migrations\" namespace.\n\nDid you mean one of these?\n    doctrine\n    doctrine:cache\n    doctrine:database\n    doctrine:generate\n    doctrine:mapping\n    doctrine:migrations\n    doctrine:query\n    doctrine:schema"} []
[2019-11-14 14:28:00] console.ERROR: Error thrown while running command "doctrine:migrations:migrate". Message: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES)" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:migrations:migrate","message":"An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES)"} []
[2019-11-14 14:28:00] console.DEBUG: Command "doctrine:migrations:migrate" exited with code "1" {"command":"doctrine:migrations:migrate","code":1} []
[2019-11-14 14:28:05] console.ERROR: Error thrown while running command "doctrine:migrations:migrate". Message: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES)" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:migrations:migrate","message":"An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES)"} []
[2019-11-14 14:28:05] console.DEBUG: Command "doctrine:migrations:migrate" exited with code "1" {"command":"doctrine:migrations:migrate","code":1} []
[2019-11-14 14:28:49] console.ERROR: Error thrown while running command "'doctrine:migrations:create'". Message: "Command "doctrine:migrations:create" is not defined.  Did you mean one of these?     doctrine:database:create     doctrine:migrations:diff     doctrine:migrations:dump-schema     doctrine:migrations:execute     doctrine:migrations:generate     doctrine:migrations:latest     doctrine:migrations:migrate     doctrine:migrations:rollup     doctrine:migrations:status     doctrine:migrations:up-to-date     doctrine:migrations:version     doctrine:schema:create     make:migration" {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): Command \"doctrine:migrations:create\" is not defined.\n\nDid you mean one of these?\n    doctrine:database:create\n    doctrine:migrations:diff\n    doctrine:migrations:dump-schema\n    doctrine:migrations:execute\n    doctrine:migrations:generate\n    doctrine:migrations:latest\n    doctrine:migrations:migrate\n    doctrine:migrations:rollup\n    doctrine:migrations:status\n    doctrine:migrations:up-to-date\n    doctrine:migrations:version\n    doctrine:schema:create\n    make:migration at /var/www/workflow-consolidation-challenge/vendor/symfony/console/Application.php:660)","command":"'doctrine:migrations:create'","message":"Command \"doctrine:migrations:create\" is not defined.\n\nDid you mean one of these?\n    doctrine:database:create\n    doctrine:migrations:diff\n    doctrine:migrations:dump-schema\n    doctrine:migrations:execute\n    doctrine:migrations:generate\n    doctrine:migrations:latest\n    doctrine:migrations:migrate\n    doctrine:migrations:rollup\n    doctrine:migrations:status\n    doctrine:migrations:up-to-date\n    doctrine:migrations:version\n    doctrine:schema:create\n    make:migration"} []
[2019-11-14 14:29:01] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES)" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES)"} []
[2019-11-14 14:29:01] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2019-11-14 14:30:08] console.ERROR: Error thrown while running command "make:migration". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"make:migration","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2019-11-14 14:30:08] console.DEBUG: Command "make:migration" exited with code "1" {"command":"make:migration","code":1} []
[2019-11-14 14:30:34] console.ERROR: Error thrown while running command "make:migration". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"make:migration","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2019-11-14 14:30:34] console.DEBUG: Command "make:migration" exited with code "1" {"command":"make:migration","code":1} []
[2019-11-14 14:30:45] console.ERROR: Error thrown while running command "make:migration". Message: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES)" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"make:migration","message":"An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES)"} []
[2019-11-14 14:30:45] console.DEBUG: Command "make:migration" exited with code "1" {"command":"make:migration","code":1} []
[2019-11-14 14:31:39] console.ERROR: Error thrown while running command "make:migration". Message: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES)" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"make:migration","message":"An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES)"} []
[2019-11-14 14:31:39] console.DEBUG: Command "make:migration" exited with code "1" {"command":"make:migration","code":1} []
[2019-11-14 14:33:03] console.ERROR: Error thrown while running command "make:migration". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"make:migration","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2019-11-14 14:33:03] console.DEBUG: Command "make:migration" exited with code "1" {"command":"make:migration","code":1} []
[2019-11-14 14:34:28] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2019-11-14 14:34:28] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2019-11-14 14:36:26] console.ERROR: Error thrown while running command "make:migration". Message: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES)" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"make:migration","message":"An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES)"} []
[2019-11-14 14:36:26] console.DEBUG: Command "make:migration" exited with code "1" {"command":"make:migration","code":1} []
[2019-11-14 14:41:27] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"http://symfony.local/register","method":"GET"} []
[2019-11-14 14:41:27] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-11-14 14:41:29] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Neither the property "name" nor one of the methods "name()", "getname()"/"isname()"/"hasname()" or "__call()" exist and have public access in class "Symfony\Component\Form\FormView"." at /var/www/workflow-consolidation-challenge/templates/registration/register.html.twig line 9 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Neither the property \"name\" nor one of the methods \"name()\", \"getname()\"/\"isname()\"/\"hasname()\" or \"__call()\" exist and have public access in class \"Symfony\\Component\\Form\\FormView\". at /var/www/workflow-consolidation-challenge/templates/registration/register.html.twig:9)"} []
[2019-11-14 14:41:31] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"ac235f"},"request_uri":"http://symfony.local/_wdt/ac235f","method":"GET"} []
[2019-11-14 14:42:16] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"http://symfony.local/register","method":"GET"} []
[2019-11-14 14:42:16] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-11-14 14:42:17] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"dd6a9e"},"request_uri":"http://symfony.local/_wdt/dd6a9e","method":"GET"} []
[2019-11-14 14:42:20] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico"" at /var/www/workflow-consolidation-challenge/vendor/symfony/http-kernel/EventListener/RouterListener.php line 138 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /var/www/workflow-consolidation-challenge/vendor/symfony/http-kernel/EventListener/RouterListener.php:138, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/workflow-consolidation-challenge/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2019-11-14 15:07:23] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"http://symfony.local/register","method":"GET"} []
[2019-11-14 15:07:24] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-11-14 15:07:25] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"49a7a4"},"request_uri":"http://symfony.local/_wdt/49a7a4","method":"GET"} []
[2019-11-14 16:14:45] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"http://symfony.local/register","method":"GET"} []
[2019-11-14 16:14:45] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-11-14 16:14:46] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"8d0b1a"},"request_uri":"http://symfony.local/_wdt/8d0b1a","method":"GET"} []
[2019-11-14 16:17:26] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /index.html"" at /var/www/workflow-consolidation-challenge/vendor/symfony/http-kernel/EventListener/RouterListener.php line 138 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /index.html\" at /var/www/workflow-consolidation-challenge/vendor/symfony/http-kernel/EventListener/RouterListener.php:138, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/index.html/\". at /var/www/workflow-consolidation-challenge/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2019-11-14 16:17:27] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"af2764"},"request_uri":"http://symfony.local/_wdt/af2764","method":"GET"} []
[2019-11-14 16:17:28] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"af2764"},"request_uri":"http://symfony.local/_wdt/af2764","method":"GET"} []
[2019-11-14 16:17:35] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /index.html.twig"" at /var/www/workflow-consolidation-challenge/vendor/symfony/http-kernel/EventListener/RouterListener.php line 138 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /index.html.twig\" at /var/www/workflow-consolidation-challenge/vendor/symfony/http-kernel/EventListener/RouterListener.php:138, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/index.html.twig/\". at /var/www/workflow-consolidation-challenge/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2019-11-14 16:17:35] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"c25579"},"request_uri":"http://symfony.local/_wdt/c25579","method":"GET"} []
[2019-11-14 16:17:36] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"c25579"},"request_uri":"http://symfony.local/_wdt/c25579","method":"GET"} []
[2019-11-14 16:34:12] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /index"" at /var/www/workflow-consolidation-challenge/vendor/symfony/http-kernel/EventListener/RouterListener.php line 138 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /index\" at /var/www/workflow-consolidation-challenge/vendor/symfony/http-kernel/EventListener/RouterListener.php:138, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/index/\". at /var/www/workflow-consolidation-challenge/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2019-11-14 16:34:12] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"5194a4"},"request_uri":"http://symfony.local/_wdt/5194a4","method":"GET"} []
[2019-11-14 16:34:13] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"5194a4"},"request_uri":"http://symfony.local/_wdt/5194a4","method":"GET"} []
[2019-11-14 16:34:40] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /base"" at /var/www/workflow-consolidation-challenge/vendor/symfony/http-kernel/EventListener/RouterListener.php line 138 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /base\" at /var/www/workflow-consolidation-challenge/vendor/symfony/http-kernel/EventListener/RouterListener.php:138, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/base/\". at /var/www/workflow-consolidation-challenge/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2019-11-14 16:34:40] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"46a727"},"request_uri":"http://symfony.local/_wdt/46a727","method":"GET"} []
[2019-11-14 16:34:41] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"46a727"},"request_uri":"http://symfony.local/_wdt/46a727","method":"GET"} []
[2019-11-14 16:37:06] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"http://symfony.local/register","method":"POST"} []
[2019-11-14 16:37:06] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-11-14 16:37:07] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES)" at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 93 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)"} []
[2019-11-14 16:37:08] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"226cdb"},"request_uri":"http://symfony.local/_wdt/226cdb","method":"GET"} []
[2019-11-14 16:37:09] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"226cdb"},"request_uri":"http://symfony.local/_wdt/226cdb","method":"GET"} []
[2019-11-14 16:55:56] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"http://symfony.local/register","method":"POST"} []
[2019-11-14 16:55:56] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-11-14 16:55:56] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES)" at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 93 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'jeroen'@'localhost' (using password: YES) at /var/www/workflow-consolidation-challenge/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)"} []
[2019-11-14 16:55:56] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"25745c"},"request_uri":"http://symfony.local/_wdt/25745c","method":"GET"} []
[2019-11-14 16:55:58] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"25745c"},"request_uri":"http://symfony.local/_wdt/25745c","method":"GET"} []
[2019-11-15 09:33:03] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"http://symfony.local/register","method":"GET"} []
[2019-11-15 09:33:03] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-11-15 09:33:06] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"8fbc13"},"request_uri":"http://symfony.local/_wdt/8fbc13","method":"GET"} []
[2019-11-15 10:38:12] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"http://symfony.local/register","method":"POST"} []
[2019-11-15 10:38:12] request.CRITICAL: Uncaught PHP Exception ErrorException: "Notice: SessionHandler::gc(): ps_files_cleanup_dir: opendir(/var/lib/php/sessions) failed: Permission denied (13)" at /var/www/workflow-consolidation-challenge/vendor/symfony/http-foundation/Session/Storage/Handler/StrictSessionHandler.php line 101 {"exception":"[object] (ErrorException(code: 0): Notice: SessionHandler::gc(): ps_files_cleanup_dir: opendir(/var/lib/php/sessions) failed: Permission denied (13) at /var/www/workflow-consolidation-challenge/vendor/symfony/http-foundation/Session/Storage/Handler/StrictSessionHandler.php:101)"} []
[2019-11-15 10:38:13] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"635089"},"request_uri":"http://symfony.local/_wdt/635089","method":"GET"} []
[2019-11-27 12:15:01] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"635089"},"request_uri":"http://symfony.local/_wdt/635089","method":"GET"} []
[2019-11-27 12:15:01] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"http://symfony.local/register","method":"GET"} []
[2019-11-27 12:15:02] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
